services:
  - type: web
    name: cookie-energie
    env: python
    region: Singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
